#Pandas

In [2]:
#b c
import pandas as pd
data = pd.read_csv('Salaries.csv',skiprows=[1])#,index_col='playerID',header = 0
data = data.set_index('playerID')
data.head()

yearID teamID lgID  salary
playerID                             
bedrost01    1985    ATL   NL  550000
benedbr01    1985    ATL   NL  545000
campri01     1985    ATL   NL  633333
ceronri01    1985    ATL   NL  625000
chambch01    1985    ATL   NL  800000

In [3]:
#d
d = data.loc[(data.teamID.isin(['ATL','HOU'])) & (data.salary > 1000000)]
selected_id = d.index
selected_id

Index(['hornebo01', 'murphda05', 'suttebr01', 'ryanno01', 'hornebo01',
       'murphda05', 'suttebr01', 'ryanno01', 'griffke01', 'murphda05',
       ...
       'feldmsc01', 'gonzama01', 'gregelu01', 'lowrije01', 'neshepa01',
       'quallch01', 'rasmuco01', 'singljo02', 'sippto01', 'valbulu01'],
      dtype='object', name='playerID', length=595)

In [4]:
#e
team_ATL = data.loc[data.teamID == 'ATL']
team_ATL_summary = team_ATL['salary'].describe()
team_ATL_summary

count    8.850000e+02
mean     2.207749e+06
std      3.434320e+06
min      6.000000e+04
25%      3.000000e+05
50%      6.000000e+05
75%      2.400000e+06
max      1.606180e+07
Name: salary, dtype: float64

In [5]:
#f
dict = {}
for index,row in data.iterrows():
  for column_name,value in row.items():
    if column_name not in dict:
      dict[column_name] = []
    dict[column_name].append(value)
print(dict)

{'yearID': [1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985, 1985

In [6]:
# to_dict method
data_dict2= data.to_dict()
print(data_dict2)

{'yearID': {'bedrost01': 1995, 'benedbr01': 1989, 'campri01': 1986, 'ceronri01': 1992, 'chambch01': 1986, 'dedmoje01': 1988, 'forstte01': 1986, 'garbege01': 1988, 'harpete01': 1987, 'hornebo01': 1988, 'hubbagl01': 1988, 'mahleri01': 1990, 'mcmurcr01': 1995, 'mumphje01': 1988, 'murphda05': 1993, 'oberkke01': 1991, 'perezpa01': 1991, 'perryge01': 1995, 'ramirra01': 1992, 'suttebr01': 1990, 'washicl01': 1990, 'boddimi01': 1993, 'dauerri01': 1985, 'davisst02': 1994, 'dempsri01': 1992, 'dwyerji01': 1990, 'flanami01': 1992, 'fordda01': 1986, 'grosswa01': 1986, 'lacyle01': 1987, 'lynnfr01': 1990, 'martide01': 1998, 'martiti01': 1986, 'mcgresc01': 1988, 'murraed02': 1997, 'nolanjo01': 1985, 'rayfofl01': 1987, 'ripkeca01': 2001, 'roeniga01': 1988, 'sheetla01': 1990, 'shelbjo01': 1991, 'stewasa01': 1987, 'youngmi01': 1989, 'armasto01': 1989, 'barrema02': 1990, 'boggswa01': 1999, 'bordiri01': 1986, 'boydoi01': 1991, 'bucknbi01': 1989, 'clearma01': 1988, 'clemero02': 2005, 'crawfst01': 1990, 'easl

In [7]:
#g
import string
g = pd.DataFrame.from_dict(data_dict2)
g.head()
g.shape
#change header
#new = list(string.ascii_lowercase)[:g.shape[0]]
#g.set_index('header')

(4963, 4)

#Numpy

In [ ]:
import numpy as np
#a
a = [
    [1,2,3],
    [4,5,6]
]
nparray = np.array(a)
print(nparray)

[[1 2 3]
 [4 5 6]]


In [ ]:
#b
print(nparray.ndim)
print(nparray.shape)
print(nparray.size)
print(nparray.dtype)
print(nparray.itemsize)
print(nparray.data)

2
(2, 3)
6
int64
8


In [ ]:
#c
c=nparray.reshape(3,2)
c.shape
print(c)
c2=c.flatten()
print(c2)

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [ ]:
#d slices
x = np.array([2,5,1,9,0,3,8,11,-4,-3,-8,6,10])
print(x[0])

2


In [ ]:
y = np.arange(42).reshape(6,7)
print(y)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]]


In [ ]:
print(y[:,0])

[ 0  7 14 21 28 35]


In [ ]:
#Learn operations on ndarray by examining the argmin(), argmax(), min(), max(),
#mean(), sum(), std(), dot(), square(), sqrt(), abs(). exp(), sign(), and mod()
#methods. Make yourself comfortable with these methods.
print(np.argmin(y))
print(np.argmax(y))
print(np.min(y))
print(np.max(y))
print(np.mean(y))

0
41
0
41
20.5


In [ ]:
a = np.array([[1, 2], [3, 4]])
print(a)
np.mean(a)

[[1 2]
 [3 4]]


2.5

In [ ]:
# arange(), ones(), zeros(), eye(), linspace(), and concatenate()


#Scikit-Learn

In [ ]:
#KNeighborsClassifier
#linear regression
#logistic regression
#feature selection

In [ ]:
#stratified k-fold cross validation
#repeated